#!/bin/sh
# This script will edit the file named as the first argument in-place.
ed -s "$1" <<EOF
/^  addr:/c
  addr: :${registry_port:-5000}
.
/^    realm:/c
    realm: ${protocol:-http}://${gitlab_host:-127.0.0.1}:${gitlab_port:-3000}/jwt/auth
.
wq
EOF
